Fix error creating WebhookEndpoint in admin panel
sqlite3.IntegrityError: NOT NULL constraint failed: djstripe_webhookendpoint.tolerance

Fixes #1955

(cherry picked from commit 470924bfb5f3cbf14d4f6af005a21afcac56b4cb)